from datetime import datetime
from pathlib import Path
from tests.compare._csv_comparator import CSVComparator
from tests.compare._name_mapping import get_python_folder
from tests._utils import discover_test_datasets


def _resolve_project_path(project_root, path):
    path = Path(path)
    return path if path.is_absolute() else project_root / path


def run_comparison_suite(project_root, matlab_test_name,
                         ref_folder="reference_output",
                         out_folder="test_output",
                         structure="nested",
                         variables=None,
                         threshold=None,
                         enable_logging=False,
                         log_lines_output=None):
    """
    Generic runner for comparing MATLAB vs Python test results.

    Args:
        structure (str):
            - "nested": root / dataset / test_name (Default, e.g. sineFit)
            - "flat":   root / test_name (Simple, e.g. test_basic)
        variables (list): Optional MATLAB/Python variable stems to compare.
            When omitted, compare every *_python.csv generated by Python.
        threshold (float): Optional absolute-difference threshold for this suite.
        enable_logging (bool): If True, creates individual log file for this test
        log_lines_output (list): If provided, appends log lines to this list instead of file
    """
    # 1. Setup
    ref_root = _resolve_project_path(project_root, ref_folder)  # Reference Data Root
    gen_root = _resolve_project_path(project_root, out_folder)  # Generated Data Root
    python_test_name = get_python_folder(matlab_test_name)

    # Setup logging
    if log_lines_output is None:
        log_lines = []
    else:
        log_lines = log_lines_output

    def log(msg):
        """Print and log message"""
        print(msg)
        log_lines.append(msg)

    comparator = CSVComparator(threshold=threshold)
    log(f"[Comparison Test: {python_test_name}] <-> [MATLAB Test: {matlab_test_name}]")
    log(f"[Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] [Mode: {structure.upper()}] [Threshold: {comparator.threshold:.2e}]")

    # -------------------------------------------------------
    # 2. Logic Branching: Determine Datasets & Paths
    # -------------------------------------------------------
    comparison_targets = []  # List of (display_name, mat_dir, py_dir)

    if structure == "nested":
        # Scenario: root / dataset / test_name
        datasets = discover_test_datasets(ref_root, subfolder=matlab_test_name)
        if not datasets:
            raise AssertionError(
                f"No reference datasets found in {ref_root} containing '{matlab_test_name}'"
            )

        for ds in datasets:
            mat_dir = ref_root / ds / matlab_test_name
            py_dir = gen_root / ds / python_test_name
            comparison_targets.append((ds, mat_dir, py_dir))

    elif structure == "flat":
        # Scenario: root / test_name (No dataset layer)
        # We treat the test name itself as the "dataset" for display purposes
        mat_dir = ref_root / matlab_test_name
        py_dir = gen_root / python_test_name

        # Check if the folder exists at all
        if not mat_dir.exists():
            raise AssertionError(f"Flat reference folder not found: {mat_dir}")

        comparison_targets.append(("Single", mat_dir, py_dir))

    else:
        raise ValueError(f"Unknown structure mode: {structure}")

    # -------------------------------------------------------
    # 3. Execution Loop (Common Logic)
    # -------------------------------------------------------
    failures = []
    total_checks = 0

    for display_name, mat_dir, py_dir in comparison_targets:
        log(f"\n[{py_dir}] <-> [{mat_dir}]")

        # Check Directory (Python-Centric: skip if Python didn't generate it)
        if not py_dir.exists():
            log(f"  -> [FAIL] Python directory not found: {py_dir}")
            failures.append(f"{display_name}: Python directory not found: {py_dir}")
            continue

        if variables is None:
            # Discover Variables (Python-Centric: scan what Python generated)
            python_csv_files = sorted(py_dir.glob("*_python.csv"))
            if not python_csv_files:
                log(f"  -> [FAIL] No Python output files found in {py_dir}")
                failures.append(f"{display_name}: No Python output files found in {py_dir}")
                continue

            # Extract variable names from Python files
            target_variables = [f.stem.replace("_python", "") for f in python_csv_files]
        else:
            target_variables = list(variables)

        max_len = max((len(v) for v in target_variables), default=8)
        max_len = max(max_len, 8)

        for var in target_variables:
            total_checks += 1
            py_csv = py_dir / f"{var}_python.csv"
            mat_csv = mat_dir / f"{var}_matlab.csv"

            if not py_csv.exists():
                log(f"  [{var:<{max_len}}] -> [FAIL] No Python output: {py_csv}")
                failures.append(f"{display_name}/{var}: No Python output: {py_csv}")
                continue

            # Check if MATLAB reference exists (Skip if no reference, not FAIL)
            if not mat_csv.exists():
                log(f"  [{var:<{max_len}}] -> [FAIL] No MATLAB reference: {mat_csv}")
                failures.append(f"{display_name}/{var}: No MATLAB reference: {mat_csv}")
                continue

            # Compare
            result = comparator.compare_pair(py_csv, mat_csv)
            status = result['status']
            diff_abs = result['max_diff_abs']
            diff_rel = result.get('max_diff_rel', 0)
            error = result.get('error') or result.get('msg')

            # Format output with both absolute and relative errors
            if diff_rel < 0.01:  # Less than 0.01% - show absolute only
                msg = f"  [{var:<{max_len}}]: [Abs: {diff_abs:.2e}] -> [{status:<8}]"
            else:
                msg = f"  [{var:<{max_len}}]: [Abs: {diff_abs:.2e}, Rel: {diff_rel:.4f}%] -> [{status:<8}]"

            if status == "PERFECT":
                log(msg)
            else:
                log(f"{msg} <--- FAIL")
                detail = f"{display_name}/{var}: {status} (Abs: {diff_abs:.2e}, Rel: {diff_rel:.4f}%)"
                if error:
                    detail += f" error={error}"
                failures.append(detail)

    # 4. Summary
    log("-" * 60)
    log(f"[SUMMARY] Verified {total_checks} files.")

    if not comparison_targets:
        raise AssertionError("No comparison targets were discovered.")

    if total_checks == 0 and not failures:
        raise AssertionError("No comparison files were checked.")

    if failures:
        log("\n[FAILURES DETAILS]")
        log("\n".join(f"  x {f}" for f in failures))

    # Save log file if enabled and not using external log
    if enable_logging and log_lines_output is None:
        log_dir = project_root / "test_comparison_logs"
        log_dir.mkdir(exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        log_file = log_dir / f"{python_test_name}_{timestamp}.txt"
        log(f"\n[Log saved to: {log_file}]")
        log_file.write_text('\n'.join(log_lines), encoding='utf-8')

    if failures:
        raise AssertionError(
            f"Comparison failed for {len(failures)} item(s):\n"
            + "\n".join(f"  - {failure}" for failure in failures)
        )
